# Generated by Django 4.0.4 on 2022-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planogram',
            name='descripton',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='descripton',
            field=models.TextField(default=None),
        ),
    ]
