# Generated by Django 4.0.4 on 2022-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0002_planogram_descripton_product_descripton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='planogram_photo',
            field=models.ImageField(upload_to='planograms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='result_image_name',
            field=models.ImageField(upload_to='resultimages'),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='photo_name',
            field=models.ImageField(upload_to='images'),
        ),
    ]
