# Generated by Django 4.0.4 on 2022-06-09 06:45

from django.db import migrations, models
import layouts.models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0003_alter_planogram_planogram_photo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComanyProduct',
            new_name='CompanyProduct',
        ),
        migrations.RenameField(
            model_name='planogram',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='planogram',
            name='planogram_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to=layouts.models.get_products_path),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='result_image_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='photo_name',
            field=models.ImageField(upload_to=layouts.models.get_store_path),
        ),
    ]
