# Generated by Django 4.0.4 on 2022-06-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0004_rename_comanyproduct_companyproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
