# Generated by Django 4.0.4 on 2022-07-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0005_product_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='detected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='store_id',
            field=models.IntegerField(default=0),
        ),
    ]
